import type { Ingredient, Product, SkinConcern } from "./types";

export const INGREDIENTS: Ingredient[] = [
  {
    id: "retinol",
    name: "Retinol",
    inci: "Retinol",
    description:
      "A vitamin A derivative that accelerates cell turnover, stimulates collagen production, and reduces the appearance of fine lines and hyperpigmentation.",
    benefits: [
      "Reduces fine lines and wrinkles",
      "Improves skin texture",
      "Fades hyperpigmentation",
      "Unclogs pores",
      "Stimulates collagen synthesis",
    ],
    concerns: ["anti-aging", "acne", "hyperpigmentation", "texture", "pores"],
    skinTypes: ["normal", "combination", "oily"],
    concentrationRange: {
      min: 0.025,
      max: 1.0,
      optimal: 0.3,
      unit: "%",
    },
    function: ["retinoid"],
    safetyRating: "moderate",
    comedogenic: 0,
    interactions: {
      compatible: ["hyaluronic-acid", "niacinamide", "peptides"],
      avoid: ["aha-bha", "vitamin-c", "benzoyl-peroxide"],
    },
    sources: ["Vitamin A"],
    ph: { min: 5.5, max: 7.0 },
    tags: ["anti-aging", "cell-turnover", "collagen-boost"],
  },
  {
    id: "hyaluronic-acid",
    name: "Hyaluronic Acid",
    inci: "Sodium Hyaluronate",
    description:
      "A powerful humectant naturally found in the skin that holds up to 1000x its weight in water, providing deep hydration and plumping effects.",
    benefits: [
      "Intense hydration",
      "Plumps skin",
      "Reduces appearance of fine lines",
      "Improves skin elasticity",
      "Suitable for all skin types",
    ],
    concerns: ["dryness", "fine-lines", "anti-aging"],
    skinTypes: ["dry", "oily", "combination", "normal", "sensitive"],
    concentrationRange: {
      min: 0.1,
      max: 2.0,
      optimal: 1.0,
      unit: "%",
    },
    function: ["humectant"],
    safetyRating: "low",
    comedogenic: 0,
    interactions: {
      compatible: ["retinol", "vitamin-c", "niacinamide", "aha-bha", "peptides"],
      avoid: [],
    },
    sources: ["Fermentation", "Animal-derived (rooster comb)"],
    tags: ["hydration", "plumping", "universal"],
  },
  {
    id: "niacinamide",
    name: "Niacinamide",
    inci: "Niacinamide",
    description:
      "Vitamin B3 that regulates sebum production, minimizes pores, brightens skin tone, and reduces inflammation — one of the most versatile skincare ingredients.",
    benefits: [
      "Minimizes pores",
      "Regulates oil production",
      "Fades dark spots",
      "Strengthens skin barrier",
      "Reduces redness",
    ],
    concerns: ["oiliness", "pores", "hyperpigmentation", "redness", "acne"],
    skinTypes: ["oily", "combination", "sensitive", "normal"],
    concentrationRange: {
      min: 2.0,
      max: 20.0,
      optimal: 10.0,
      unit: "%",
    },
    function: ["brightener", "anti-inflammatory"],
    safetyRating: "low",
    comedogenic: 0,
    interactions: {
      compatible: ["hyaluronic-acid", "aha-bha", "retinol", "zinc"],
      avoid: [],
    },
    sources: ["Synthetic"],
    tags: ["brightening", "pore-minimizing", "barrier-repair"],
  },
  {
    id: "vitamin-c",
    name: "Vitamin C (L-Ascorbic Acid)",
    inci: "Ascorbic Acid",
    description:
      "A potent antioxidant that brightens skin, stimulates collagen production, protects against UV damage, and fades hyperpigmentation.",
    benefits: [
      "Brightens complexion",
      "Fades hyperpigmentation",
      "Boosts collagen production",
      "Antioxidant protection",
      "Evens skin tone",
    ],
    concerns: ["hyperpigmentation", "anti-aging", "uneven-tone"],
    skinTypes: ["normal", "combination", "oily"],
    concentrationRange: {
      min: 5.0,
      max: 20.0,
      optimal: 15.0,
      unit: "%",
    },
    function: ["antioxidant", "brightener"],
    safetyRating: "moderate",
    comedogenic: 0,
    interactions: {
      compatible: ["vitamin-e", "ferulic-acid", "hyaluronic-acid", "sunscreen"],
      avoid: ["retinol", "niacinamide", "aha-bha"],
    },
    sources: ["Synthetic", "Citrus fruits"],
    ph: { min: 2.5, max: 3.5 },
    tags: ["brightening", "antioxidant", "collagen-boost"],
  },
  {
    id: "aha-bha",
    name: "AHA/BHA (Glycolic + Salicylic Acid)",
    inci: "Glycolic Acid / Salicylic Acid",
    description:
      "Alpha and beta hydroxy acids that chemically exfoliate dead skin cells, unclog pores, and improve texture. AHAs are water-soluble; BHAs are oil-soluble.",
    benefits: [
      "Exfoliates dead skin cells",
      "Unclogs pores",
      "Improves texture",
      "Reduces acne",
      "Brightens skin",
    ],
    concerns: ["acne", "texture", "pores", "hyperpigmentation", "oiliness"],
    skinTypes: ["oily", "combination", "normal"],
    concentrationRange: {
      min: 0.5,
      max: 10.0,
      optimal: 2.0,
      unit: "%",
    },
    function: ["exfoliant"],
    safetyRating: "moderate",
    comedogenic: 0,
    interactions: {
      compatible: ["hyaluronic-acid", "niacinamide"],
      avoid: ["retinol", "vitamin-c", "benzoyl-peroxide"],
    },
    sources: ["Sugarcane (glycolic)", "Willow bark (salicylic)"],
    ph: { min: 3.0, max: 4.0 },
    tags: ["exfoliation", "acne-fighting", "texture"],
  },
  {
    id: "ceramides",
    name: "Ceramides",
    inci: "Ceramide NP / Ceramide AP / Ceramide EOP",
    description:
      "Lipids naturally found in the skin's outer layer that maintain the barrier, lock in moisture, and protect against environmental damage.",
    benefits: [
      "Restores skin barrier",
      "Locks in moisture",
      "Reduces sensitivity",
      "Smooths skin texture",
      "Protects against irritants",
    ],
    concerns: ["dryness", "redness", "eczema"],
    skinTypes: ["dry", "sensitive", "normal", "combination"],
    concentrationRange: {
      min: 0.5,
      max: 5.0,
      optimal: 2.0,
      unit: "%",
    },
    function: ["emollient", "film-former"],
    safetyRating: "low",
    comedogenic: 1,
    interactions: {
      compatible: ["hyaluronic-acid", "niacinamide", "peptides", "cholesterol"],
      avoid: [],
    },
    sources: ["Synthetic", "Plant-derived"],
    tags: ["barrier-repair", "moisturizing", "sensitive-friendly"],
  },
  {
    id: "peptides",
    name: "Peptides (Matrixyl 3000)",
    inci: "Palmitoyl Tripeptide-1 / Palmitoyl Tetrapeptide-7",
    description:
      "Short chains of amino acids that signal skin cells to produce more collagen and elastin, reducing the appearance of fine lines and firming skin.",
    benefits: [
      "Stimulates collagen production",
      "Firms and tightens skin",
      "Reduces fine lines",
      "Improves elasticity",
      "Gentle on sensitive skin",
    ],
    concerns: ["anti-aging", "fine-lines"],
    skinTypes: ["dry", "normal", "combination", "sensitive"],
    concentrationRange: {
      min: 0.01,
      max: 0.5,
      optimal: 0.1,
      unit: "%",
    },
    function: ["peptide"],
    safetyRating: "low",
    comedogenic: 0,
    interactions: {
      compatible: ["hyaluronic-acid", "niacinamide", "retinol", "ceramides"],
      avoid: ["aha-bha"],
    },
    sources: ["Synthetic"],
    tags: ["anti-aging", "collagen", "firming"],
  },
  {
    id: "azelaic-acid",
    name: "Azelaic Acid",
    inci: "Azelaic Acid",
    description:
      "A dicarboxylic acid with antibacterial, anti-inflammatory, and brightening properties. Particularly effective for rosacea, acne, and post-inflammatory hyperpigmentation.",
    benefits: [
      "Reduces redness and rosacea",
      "Treats acne",
      "Fades post-inflammatory marks",
      "Evens skin tone",
      "Gentle exfoliation",
    ],
    concerns: ["acne", "rosacea", "hyperpigmentation", "redness"],
    skinTypes: ["sensitive", "oily", "combination", "normal"],
    concentrationRange: {
      min: 5.0,
      max: 20.0,
      optimal: 10.0,
      unit: "%",
    },
    function: ["anti-acne", "brightener", "anti-inflammatory"],
    safetyRating: "low",
    comedogenic: 0,
    interactions: {
      compatible: ["hyaluronic-acid", "niacinamide", "retinol"],
      avoid: [],
    },
    sources: ["Wheat", "Barley", "Rye", "Synthetic"],
    tags: ["rosacea", "acne", "gentle"],
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "cerave-moisturizing-cream",
    name: "Moisturizing Cream",
    brand: "CeraVe",
    category: "moisturizer",
    price: 16.99,
    size: "16 oz",
    description:
      "Developed with dermatologists, this non-comedogenic moisturizer with three essential ceramides and hyaluronic acid restores and maintains the skin's natural barrier.",
    keyIngredients: ["ceramides", "hyaluronic-acid", "niacinamide"],
    allIngredients: ["ceramides", "hyaluronic-acid", "niacinamide"],
    concerns: ["dryness", "eczema"],
    skinTypes: ["dry", "normal", "sensitive"],
    rating: 4.8,
    reviewCount: 125430,
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&q=80",
    purchaseLinks: [
      { retailer: "Target", url: "#", price: 16.99, inStock: true },
      { retailer: "CVS", url: "#", price: 17.49, inStock: true },
      { retailer: "Amazon", url: "#", price: 15.98, inStock: true },
    ],
    tags: ["drugstore", "fragrance-free", "derm-recommended"],
  },
  {
    id: "ordinary-retinol",
    name: "Retinol 0.5% in Squalane",
    brand: "The Ordinary",
    category: "serum",
    price: 11.9,
    size: "30 ml",
    description:
      "Moderate-strength retinol solution in a squalane base to minimize irritation while delivering visible anti-aging results.",
    keyIngredients: ["retinol"],
    allIngredients: ["retinol", "squalane"],
    concerns: ["anti-aging", "fine-lines", "texture"],
    skinTypes: ["normal", "combination", "oily"],
    rating: 4.5,
    reviewCount: 34200,
    imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&q=80",
    purchaseLinks: [
      { retailer: "Sephora", url: "#", price: 11.9, inStock: true },
      { retailer: "ULTA", url: "#", price: 11.9, inStock: true },
    ],
    tags: ["affordable", "beginner-retinol", "vegan"],
  },
  {
    id: "paulas-choice-bha",
    name: "Skin Perfecting 2% BHA Liquid Exfoliant",
    brand: "Paula's Choice",
    category: "exfoliant",
    price: 34.0,
    size: "4 oz",
    description:
      "Cult-favorite leave-on exfoliant with 2% salicylic acid that unclogs pores, smooths wrinkles, and evens skin tone.",
    keyIngredients: ["aha-bha"],
    allIngredients: ["aha-bha", "niacinamide"],
    concerns: ["acne", "pores", "texture", "oiliness"],
    skinTypes: ["oily", "combination", "normal"],
    rating: 4.7,
    reviewCount: 89000,
    imageUrl: "https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=400&q=80",
    purchaseLinks: [
      { retailer: "Sephora", url: "#", price: 34.0, inStock: true },
      { retailer: "ULTA", url: "#", price: 34.0, inStock: true },
      { retailer: "paulaschoice.com", url: "#", price: 34.0, inStock: true },
    ],
    tags: ["cult-favorite", "dermatologist-approved", "cruelty-free"],
  },
  {
    id: "skinceuticals-vitamin-c",
    name: "C E Ferulic",
    brand: "SkinCeuticals",
    category: "serum",
    price: 182.0,
    size: "30 ml",
    description:
      "Daytime vitamin C antioxidant serum with 15% L-ascorbic acid, 1% vitamin E, and 0.5% ferulic acid for advanced environmental protection.",
    keyIngredients: ["vitamin-c"],
    allIngredients: ["vitamin-c", "vitamin-e", "ferulic-acid"],
    concerns: ["hyperpigmentation", "anti-aging", "uneven-tone"],
    skinTypes: ["normal", "dry", "combination"],
    rating: 4.9,
    reviewCount: 45000,
    imageUrl: "https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?w=400&q=80",
    purchaseLinks: [
      { retailer: "Dermstore", url: "#", price: 182.0, inStock: true },
      { retailer: "Sephora", url: "#", price: 182.0, inStock: true },
    ],
    tags: ["luxury", "gold-standard", "antioxidant"],
  },
  {
    id: "isntree-hyaluronic-toner",
    name: "Hyaluronic Acid Watery Sun Gel",
    brand: "Isntree",
    category: "toner",
    price: 22.0,
    size: "200 ml",
    description:
      "A lightweight toner packed with multiple molecular weights of hyaluronic acid for layered hydration.",
    keyIngredients: ["hyaluronic-acid"],
    allIngredients: ["hyaluronic-acid", "niacinamide"],
    concerns: ["dryness", "fine-lines"],
    skinTypes: ["dry", "sensitive", "normal", "combination"],
    rating: 4.6,
    reviewCount: 18900,
    imageUrl: "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab12?w=400&q=80",
    purchaseLinks: [
      { retailer: "YesStyle", url: "#", price: 22.0, inStock: true },
      { retailer: "Amazon", url: "#", price: 24.5, inStock: true },
    ],
    tags: ["k-beauty", "lightweight", "hydrating"],
  },
  {
    id: "la-roche-posay-cicaplast",
    name: "Cicaplast Baume B5",
    brand: "La Roche-Posay",
    category: "moisturizer",
    price: 17.0,
    size: "40 ml",
    description:
      "Multi-purpose soothing balm with panthenol and madecassoside that repairs the skin barrier and calms irritated skin.",
    keyIngredients: ["ceramides", "niacinamide"],
    allIngredients: ["ceramides", "niacinamide", "panthenol"],
    concerns: ["redness", "eczema", "dryness", "rosacea"],
    skinTypes: ["sensitive", "dry", "normal"],
    rating: 4.7,
    reviewCount: 62000,
    imageUrl: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&q=80",
    purchaseLinks: [
      { retailer: "Target", url: "#", price: 17.0, inStock: true },
      { retailer: "CVS", url: "#", price: 18.0, inStock: true },
      { retailer: "Walmart", url: "#", price: 16.5, inStock: false },
    ],
    tags: ["sensitive-skin", "fragrance-free", "barrier-repair"],
  },
];

export const SKIN_TYPE_DESCRIPTIONS: Record<string, string> = {
  dry: "Produces less sebum, feels tight or flaky. Needs extra hydration and rich moisturizers.",
  oily: "Overproduces sebum, appears shiny. Benefits from lightweight, non-comedogenic products.",
  combination: "Oily T-zone (forehead, nose, chin) with normal or dry cheeks.",
  normal: "Well-balanced — not too oily or dry. Minor issues only.",
  sensitive: "Reacts easily to products or environment. Prone to redness and irritation.",
};

export const SKIN_CONCERN_LABELS: Record<string, string> = {
  acne: "Acne & Breakouts",
  hyperpigmentation: "Hyperpigmentation",
  "anti-aging": "Anti-Aging",
  dryness: "Dryness",
  oiliness: "Excess Oil",
  redness: "Redness",
  pores: "Large Pores",
  texture: "Uneven Texture",
  "dark-circles": "Dark Circles",
  "fine-lines": "Fine Lines & Wrinkles",
  eczema: "Eczema",
  rosacea: "Rosacea",
  melasma: "Melasma",
  scarring: "Scarring",
  "uneven-tone": "Uneven Skin Tone",
};

export const AGE_RANGE_LABELS: Record<string, string> = {
  "under-18": "Under 18",
  "18-24": "18 – 24",
  "25-34": "25 – 34",
  "35-44": "35 – 44",
  "45-54": "45 – 54",
  "55+": "55+",
};

export const PRODUCT_CATEGORY_LABELS: Record<string, string> = {
  cleanser: "Cleanser",
  toner: "Toner",
  serum: "Serum",
  moisturizer: "Moisturizer",
  sunscreen: "Sunscreen",
  "eye-cream": "Eye Cream",
  exfoliant: "Exfoliant",
  mask: "Face Mask",
  oil: "Face Oil",
  mist: "Face Mist",
  "spot-treatment": "Spot Treatment",
  retinol: "Retinol",
  prescription: "Prescription",
};

export const MOCK_FOOD_RECOMMENDATIONS = {
  beneficial: [
    { name: "Fatty Fish (Salmon, Sardines)", reason: "Rich in omega-3 fatty acids that reduce inflammation and support the skin barrier.", category: "Protein" },
    { name: "Avocado", reason: "Contains healthy fats and vitamin E that nourish and hydrate skin from within.", category: "Fruit" },
    { name: "Sweet Potatoes", reason: "Packed with beta-carotene, a precursor to vitamin A that promotes cell turnover.", category: "Vegetable" },
    { name: "Green Tea", reason: "Rich in polyphenols with antioxidant and anti-inflammatory properties.", category: "Beverage" },
    { name: "Berries (Blueberries, Strawberries)", reason: "High in vitamin C and antioxidants that fight free radical damage.", category: "Fruit" },
    { name: "Walnuts", reason: "Contain essential fatty acids (omega-3 and omega-6) that maintain skin moisture.", category: "Nut" },
    { name: "Dark Chocolate (70%+)", reason: "Flavonoids improve skin texture, hydration, and UV resilience.", category: "Treat" },
  ],
  avoid: [
    { name: "High-Glycemic Foods (White bread, sugary drinks)", reason: "Spikes blood sugar, triggering inflammation and potential acne flare-ups.", category: "Carbohydrates" },
    { name: "Dairy Products", reason: "Hormones in milk may stimulate sebaceous glands and worsen acne for some.", category: "Dairy" },
    { name: "Alcohol", reason: "Dehydrates skin and depletes antioxidants, accelerating aging.", category: "Beverage" },
    { name: "Processed / Fried Foods", reason: "Trans fats and refined oils promote inflammation that shows up in skin.", category: "Processed" },
    { name: "Excessive Salt", reason: "Causes water retention and puffiness, particularly around the eyes.", category: "Seasoning" },
  ],
  supplements: [
    { name: "Vitamin D3", reason: "Many people are deficient; supports immune function and skin cell growth.", category: "Supplement" },
    { name: "Zinc", reason: "Regulates sebum production and has anti-inflammatory properties — beneficial for acne.", category: "Mineral" },
    { name: "Collagen Peptides", reason: "Oral collagen supplementation has been shown to improve skin elasticity.", category: "Protein" },
    { name: "Omega-3 (Fish Oil)", reason: "Reduces systemic inflammation that manifests as redness and breakouts.", category: "Fatty Acid" },
  ],
};
